apiVersion: v1
kind: Pod
metadata:
  name: node-selector
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always #upadted images pulled 
  nodeSelector: #select particular node name or ip
    disktype: ssd
