apiVersion: v1 
kind: Pod
metadata:   
  name: node-selector-demo-1   
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always 
  nodeSelector:
    # disktype: ssd  
    disk: ssd
  tolerations: #excuse the taints pod sceduled in tainted node 
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoExecute" #noexcute-->remove pod in node 
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule" #noschedule-->pod noscheduled in node 

